### ISSUE TITLE
Provide access to AWS Conabio account for Ec2 instances for Computer Vision data processing

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DS-issues-daily-stand-ups#1]
Will use AWS Conabio account and @jclopeze @Rebeca98 will access so they can launch instances

**Comment by palmoreck** [comment]
Will use AWS Conabio credits account inside organization that I use @omaranda :)

**Comment by omaranda** [comment]
Perfect!!! Sounds better ☺️
