### ISSUE TITLE
create a docker image for kale pipeline

### ISSUE THREAD

**Issue by Rebeca98** [biometrioearth/DS-issues-daily-stand-ups#11]
We need:

**Conda installation**
```
# Conda installation
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh \
    && . /root/miniconda3/etc/profile.d/conda.sh
```

https://github.com/Microsoft/cameratraps /lib/megadetector/cameratraps
https://github.com/Microsoft/ai4eutils /lib/megadetector/ai4eutils
https://github.com/ultralytics/yolov5/ /lib/megadetector/yolov5
`
RUN cd /lib/megadetector/yolov5 && git checkout c23a441c9df7ca9b1f275e8c8719c949269160d1
`

**use the environment:**
```
RUN cd /lib/megadetector/cameratraps && conda env create --file environment-detector.yml
SHELL ["conda", "run", "-n", "cameratraps-detector", "/bin/bash", "-c"]

```

**jupyeterlab**
`
RUN pip install --upgrade pip && pip install jupyter "jupyterlab>=2.0.0,<3.0.0" --upgrade
`

**conabio_ml_vision library**

```
RUN git clone -b dev https://bitbucket.org/conabio_cmd/conabio_ml_vision.git /lib/conabio_ml_vision
RUN pip install -r /lib/conabio_ml_vision/requirements.txt 
RUN git clone -b conabio_ml_core https://bitbucket.org/conabio_cmd/conabio_ml.git /lib/conabio_ml_vision/conabio_ml
RUN pip install -r /lib/conabio_ml_vision/conabio_ml/requirements.txt
```

**set the PYTHONPATHS**
ENV PYTHONPATH=$PYTHONPATH:/lib/conabio_ml_vision:/lib/conabio_ml_vision/conabio_ml
ENV PYTHONPATH=$PYTHONPATH:/lib/megadetector/cameratraps:/lib/megadetector/ai4eutils:/lib/megadetector/yolov5
ENV MEGADETECTOR_EXEC=/lib/megadetector/cameratraps/detection/run_detector_batch.py

**Comment by jclopeze** [comment]
The Docker image has the tag:
`biometrioearth/dev:megadetector_v5_ml_dev_0.1`

**Comment by palmoreck** [comment]
Done
