### ISSUE TITLE
Create Dockerfile for biometrioearth/dev:megadetector_v5_ml_0.1 docker image in dev-models-for-images-videos repo

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DS-issues-daily-stand-ups#12]
In repo [dev-models-for-images-and-videos](https://github.com/biometrioearth/dev-models-for-images-and-videos) create Dockerfile following same structure of directories as in [kubearth/dockerfiles/dev/megadetector_v5_ml/0.1/Dockerfile](https://github.com/biometrioearth/kubearth/blob/main/dockerfiles/dev/megadetector_v5_ml/0.1/Dockerfile) so we can configure a Github action to build&push: `biometrioearth/dev:megadetector_v5_ml_0.1` docker image when some files are changed in repo of `dev-models-for-images-and-videos`

**Comment by jclopeze** [comment]
The Docker image has the tag:

`biometrioearth/dev:megadetector_v5_ml_dev_0.1`

**Comment by palmoreck** [comment]
Done
