### ISSUE TITLE
Resolve volume integration for experiments in `kale-kubeflow`

### ISSUE THREAD

**Issue by C1587S** [biometrioearth/DS-issues-daily-stand-ups#13]
**Problem**
To store outputs from processing pipelines generated using `kale-kf` in `S3`, we must provide access to `shared_volume_s3fs`. However, to read inputs, we must provide access to  `shared_volume` (as it contains `webdav_alfdresco`). 

:arrow_forward: Given the later, we must include access to both volumes in the `kale-kf` pipeline configurations (I have not found a way to do it yet)

**Temporary solution**
The current solution is to store results in `shared_volume` and then move them to `shared_volume_s3fs`. However, this must be done outside the processing pipeline.

**Comment by palmoreck** [comment]
@C1587S how about:
<img width="305" alt="imagen" src="https://user-images.githubusercontent.com/3290689/204030038-766e62be-8a02-481b-8ecf-f86f0c7caa6d.png">

**Comment by palmoreck** [comment]
and don't forget assign this issue to Project DS. 
<img width="839" alt="imagen" src="https://user-images.githubusercontent.com/3290689/204030244-619ada28-9631-4225-a73d-e901b95dd4db.png">
I was looking for this issue in:
<img width="1272" alt="imagen" src="https://user-images.githubusercontent.com/3290689/204030348-2e86472d-e301-4fcb-ae97-722830b9af39.png">
but is not listed :)

**Comment by C1587S** [comment]
Thank you very much Erick, that solves the problem :)

**Comment by palmoreck** [comment]
great @C1587S I just noticed that I sent the screenshot for `efs` It's just a matter of using:

`/shared_volume_s3fs`

and

`hostpath-pvc-s3fs`

but i think you already figured it out :)

**Comment by palmoreck** [comment]
thanks for using Projects :)
