### ISSUE TITLE
Llenado de tablas

### ISSUE THREAD

**Issue by Rebeca98** [biometrioearth/DS-issues-daily-stand-ups#18]
llenado de tablas (Products y Annotations)

**Comment by Rebeca98** [comment]
- En la tabla Annotations agregamos la informacion relacionada a las detecciones del MD
- En la tabla de products (esta por definir si vamos a registrar los videos clasificados (empty, animal, person)

**Propuesta de metadata** (nos quedamos con los metadatos de simex que nos indique el equipo)

`{'id': '_DEFAULT_!8000000000142d5f',
 'cm_name': '11643fc7ae005142b920d7d5efcedb96_0012.mp4',
 'cm_versionLabel': '1.0',
 'cm_versionType': 'MAJOR',
 'sipecam_VideoBitsPerPixel': 24,
 'sipecam_PixelsPerMeterY': '0',
 'sipecam_StreamCount': 2,
 'sipecam_Planes': 1,
 'sipecam_AudioSampleRate': '16.0 kHz',
 'sipecam_Endianness': 'Little endian',
 'sipecam_ImageWidth': 1024,
 'sipecam_DateDeployment': '2022-01-25T00:00:00Z',
 'sipecam_BitRate': '17.5 Mbit/sec',
 'sipecam_NumChannels': 1,
 'sipecam_FileSize': 19000000,
 'sipecam_CentroidCumulusLongitude': -95.85693,
 'sipecam_BitsPerSample': 16.0,
 'sipecam_Encoding': 'Microsoft PCM',
 'sipecam_NumImportantColors': 'All',
 'sipecam_ImageHeight': 720,
 'sipecam_NodeCategoryIntegrity': 'Integro',
 'sipecam_SerialNumber': 'HLPXGM09048640',
 'sipecam_Longitude': -95.6946,
 'sipecam_ImageLength': '2211840',
 'sipecam_NomenclatureNode': '1_22_1_821',
 'sipecam_Latitude': 17.0339,
 'sipecam_EcosystemsName': 'Bosques templados',
 'sipecam_MaxDataRate': 26542080,
 'sipecam_FrameRate': 12,
 'sipecam_AvgBytesPerSec': 32050.0,
 'sipecam_Megapixels': 0.73728,
 'sipecam_PixelsPerMeterX': '0',
 'sipecam_Duration': 8.56,
 'sipecam_LongitudeRef': 'West',
 'sipecam_BMPVersion': 'Windows V3',
 'sipecam_NumColors': 'Use BitDepth',
 'sipecam_AudioSampleCount': 0,
 'sipecam_AudioCompression': 'Microsoft Pulse Code Modulation (PCM)',
 'sipecam_LatitudeRef': 'North',
 'sipecam_AudioCompressionRate': '1.0x',
 'sipecam_CumulusName': '22',
 'sipecam_CentroidCumulusLatitude': 17.01282,
 'sipecam_FrameCount': 107,
 'sipecam_DateTimeOriginal': '2022-01-25T10:27:17Z',
 'sipecam_VideoCompression': 'Motion JPEG DIB (fourcc:"MJPG")',
 'sipecam_AudioBitRate': '256.4 Kbit/sec',
 'sipecam_DateDeployment_unit_of_time_day_of_year': 25,
 'sipecam_DateTimeOriginal_unit_of_time_day_of_month': 25,
 'sipecam_DateDeployment_unit_of_time_year': 2022,
 'sipecam_DateDeployment_unit_of_time_quarter': 1,
 'sipecam_DateTimeOriginal_unit_of_time_minute': 27,
 'sipecam_DateDeployment_unit_of_time_day_of_month': 25,
 'sipecam_DateTimeOriginal_unit_of_time_quarter': 1,
 'sipecam_DateTimeOriginal_unit_of_time_month': 1,
 'sipecam_DateTimeOriginal_unit_of_time_hour': 10,
 'sipecam_DateTimeOriginal_unit_of_time_day_of_year': 25,
 'sipecam_DateDeployment_unit_of_time_month': 1,
 'sipecam_DateDeployment_unit_of_time_day_of_week': 2,
 'sipecam_DateTimeOriginal_unit_of_time_year': 2022,
 'sipecam_DateTimeOriginal_unit_of_time_second': 17,
 'sipecam_DateTimeOriginal_unit_of_time_day_of_week': 2,
 'bbox_list': {'video_frame_num': {0: 1,
   1: 1,
   2: 3,
   3: 3,
   4: 5,
   5: 5,
   6: 7,
   7: 7,
   8: 9,
   9: 9,
   10: 11,
   11: 11,
   12: 13,
   13: 13,
   14: 15,
   15: 15,
   16: 17,
   17: 17,
   18: 19,
   19: 21,
   20: 23,
   21: 25,
   22: 27,
   23: 27,
   24: 29,
   25: 29,
   26: 31,
   27: 31,
   28: 33,
   29: 35,
   30: 37,
   31: 37,
   32: 39,
   33: 41,
   34: 41,
   35: 43,
   36: 43,
   37: 45,
   38: 45,
   39: 47,
   40: 47,
   41: 47,
   42: 49,
   43: 49,
   44: 51,
   45: 51,
   46: 53,
   47: 53,
   48: 55,
   49: 55,
   50: 57,
   51: 57,
   52: 57,
   53: 57,
   54: 59,
   55: 59,
   56: 61,
   57: 61,
   58: 63,
   59: 63,
   60: 63,
   61: 65,
   62: 67,
   63: 69,
   64: 69,
   65: 71,
   66: 73,
   67: 75,
   68: 75,
   69: 77,
   70: 77,
   71: 79,
   72: 79,
   73: 79,
   74: 81,
   75: 81,
   76: 81,
   77: 83,
   78: 83,
   79: 83,
   80: 85,
   81: 85,
   82: 87,
   83: 87,
   84: 89,
   85: 89,
   86: 91,
   87: 91,
   88: 93,
   89: 93,
   90: 95,
   91: 95,
   92: 97,
   93: 97,
   94: 97,
   95: 99,
   96: 99,
   97: 101,
   98: 101,
   99: 103,
   100: 103,
   101: 105,
   102: 105,
   103: 107,
   104: 107,
   105: 107,
   106: 107,
   107: 107},
  'bbox': {0: '375,298,107,271',
   1: '687,122,337,518',
   2: '377,317,104,263',
   3: '690,124,334,507',
   4: '379,306,99,256',
   5: '685,110,297,470',
   6: '379,304,101,275',
   7: '650,99,318,459',
   8: '378,301,99,272',
   9: '676,74,290,501',
   10: '375,302,102,275',
   11: '676,66,288,507',
   12: '377,304,102,273',
   13: '682,69,278,517',
   14: '376,302,108,283',
   15: '691,75,259,527',
   16: '376,302,107,280',
   17: '686,82,250,515',
   18: '684,101,238,502',
   19: '668,97,239,504',
   20: '646,99,262,516',
   21: '641,99,290,515',
   22: '372,304,128,275',
   23: '633,104,296,510',
   24: '373,327,131,251',
   25: '612,119,293,499',
   26: '378,332,129,246',
   27: '596,122,296,498',
   28: '582,121,276,501',
   29: '571,119,277,501',
   30: '380,351,126,231',
   31: '573,132,239,487',
   32: '544,155,269,468',
   33: '390,342,117,245',
   34: '563,154,261,465',
   35: '398,329,110,252',
   36: '568,150,256,435',
   37: '400,328,106,252',
   38: '568,151,248,433',
   39: '0,631,31,72',
   40: '398,324,110,256',
   41: '569,166,241,424',
   42: '397,313,108,269',
   43: '566,184,243,432',
   44: '398,312,104,270',
   45: '550,184,260,431',
   46: '395,312,108,273',
   47: '527,185,281,417',
   48: '388,308,113,274',
   49: '526,185,284,426',
   50: '480,435,106,172',
   51: '492,458,93,87',
   52: '389,311,112,271',
   53: '545,185,263,422',
   54: '395,312,107,270',
   55: '539,185,271,425',
   56: '395,310,107,272',
   57: '553,184,256,428',
   58: '402,307,73,147',
   59: '400,307,96,270',
   60: '554,180,255,431',
   61: '531,176,279,432',
   62: '554,171,255,430',
   63: '387,303,92,280',
   64: '551,173,257,432',
   65: '519,184,290,407',
   66: '559,185,250,406',
   67: '378,303,109,275',
   68: '555,183,254,403',
   69: '368,299,115,283',
   70: '555,183,254,400',
   71: '393,301,76,155',
   72: '374,300,99,281',
   73: '553,183,256,402',
   74: '350,301,126,140',
   75: '348,302,139,280',
   76: '554,184,255,398',
   77: '382,303,99,138',
   78: '385,302,107,279',
   79: '539,184,271,400',
   80: '386,300,110,280',
   81: '526,184,284,402',
   82: '384,306,122,269',
   83: '519,185,290,403',
   84: '380,295,114,280',
   85: '538,183,272,401',
   86: '379,295,114,282',
   87: '543,184,267,402',
   88: '381,297,115,284',
   89: '541,184,269,402',
   90: '378,301,117,279',
   91: '532,184,278,401',
   92: '0,628,33,74',
   93: '379,305,116,274',
   94: '530,185,280,399',
   95: '384,300,103,276',
   96: '529,185,282,397',
   97: '384,300,103,283',
   98: '529,185,281,397',
   99: '378,303,105,269',
   100: '531,185,279,397',
   101: '333,304,142,272',
   102: '531,185,280,399',
   103: '354,306,116,147',
   104: '0,624,71,81',
   105: '0,628,32,75',
   106: '335,304,142,273',
   107: '530,184,281,402'}}}`

**Comment by Rebeca98** [comment]
@palmoreck @jclopeze en caso de no subir productos a una nueva url de s3 entonces podemos dejar vacio ese campo porque puedes recuperar el original haciendo un query hacia la tabla le files utilizando el file_id

**Comment by palmoreck** [comment]
feedback para metadatos en:

https://github.com/biometrioearth/DM-issues-daily-stand-ups/issues/18

**Comment by jclopeze** [comment]
Se cierra issue porque ya no se van a guardar los metadatos de nivel 2 en los resultados de los pipelines, sino que se consultarán directamente en cualquier lugar donde se necesiten consumir.
