### ISSUE TITLE
include Leandro's comments in dashboard for acoustic indices

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DS-issues-daily-stand-ups#25]
- [ ] plot monthly variation instead of only 24 hour graphics
- [x]  plot more information about sites (little window pop up with more site info: number of recordings, period, type of ecossystem)
- [x]  option to downloand figures
- [x]  option to plot time series of diferent sites for comparisons at the same time (just with the 7 most used acoustic indices from the literature - ACI, ADI, AEI, BI, Hf, NDSI, MED)
- [x]  button to select all/deselect indices
- [ ]  False color spectrogram only 3 indices to look clean (Acoustic Complexity Index (red), Temporal Entropy (green), and acoustic event index (blue)).
- [ ] We can have two dashboards, one with all data and indices aimed at scientists and another with only the 7 most used indices from the literature, for simplicity and non-experts.

**Comment by C1587S** [comment]
Closing and moving pending tasks to #29
