### ISSUE TITLE
Check resources given by Leandro in #bioacoustics slack channel for audio processing

### ISSUE THREAD

**Issue by palmoreck** [biometrioearth/DS-issues-daily-stand-ups#6]
- [x] `mee313964-sup-0001-supinfo.pdf`
- [x] `Screenshot_3.png` 
- [x] https://github.com/patriceguyot/Acoustic_Indices
- [x] https://scikit-maad.github.io/_auto_examples/2_advanced/plot_extract_alpha_indices.html
- [x] https://cran.r-project.org/web/packages/seewave/seewave.pdf
- [x] https://cran.r-project.org/web/packages/soundecology/soundecology.pdf
- [x] `Table_indices.docx`

**Comment by C1587S** [comment]
- A [first version](https://github.com/biometrioearth/kubearth-pipelines/tree/audio/audio/SiPeCaM/AcousticIndices) of the processing pipeline to calculate the proposed indices and generate visualizations of them for the Sipecam project is already available using the `scikit-maad` library (ref: https://scikit-maad.github.io/_auto_examples/2_advanced/plot_extract_alpha_indices.html).
